version: "3.5"

services:
  
  #  prometheus:
  #    build: ./prometheus
  #    container_name: prometheus
  #    restart: unless-stopped
  #    ports:
  #      - '9090:9090'    
  #    volumes:
  #      - prometheus:/prometheus
  
  service_a:
    image: eccbot/servicea:latest
    container_name: service_a    
    ports: 
      - "5004:80"
  
  service_b:
    image: eccbot/serviceb:latest
    container_name: service_b
    ports:
      - "5002:80"
      
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
  
  #|> Accessible jaeger port http://localhost:16686    
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: unless-stopped
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686    

volumes:
  grafana:
    driver: local
  prometheus:
    driver: local